### ISSUE TITLE
Error: Unauthorized

### ISSUE THREAD

**Issue by lovefool** [afkarxyz/spddl#1]
Hi, I am getting "Error: Unauthorized" error for downloading. 
Any reason and solutions?
Thanks in advance.

**Comment by afkarxyz** [comment]
I just checked the spotifydown API has implemented protection with cloudflare. There might be no hope anymore.

**Comment by afkarxyz** [comment]
@lovefool I have fixed it, please try again.

**Comment by lovefool** [comment]
Thanks, it works!. BTW, is it possible to change bitrate to 320K?

**Comment by afkarxyz** [comment]
Unfortunately, this alternative server is only limited to 128kbps.

**Comment by afkarxyz** [comment]
Since there's a new version, this repository will be deleted or made private. [Please check here for the replacement.](https://github.com/afkarxyz/Spotizer)
